
services:
  db:
    image: library/postgres:16
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  sentia_api:
    build:
      context: ./sentia_api
      dockerfile: Dockerfile
    volumes:
      - ./sentia_api:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: sentia_development

  sentia_frontend:
    build:
      context: ./sentia_frontend
      dockerfile: Dockerfile
    volumes:
      - ./sentia_frontend:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  pg_data:
